apiVersion: v1
kind: Service
metadata:
  name: schedulable-notebook
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hub.service.type }}
  selector:
    {{- include "jupyterhub.matchLabels" . | nindent 4 }}
  ports:
    - name: schedulable-notebook
      protocol: TCP
      port: 8888
      targetPort: 8888